spring:
  application:
    name: project-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management_system_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080